### ISSUE TITLE
Test cast for Kannada 8

### ISSUE THREAD

**Issue by MayuraVerma** [unicode-org/text-rendering-tests#22]
ಜಿ಼ೕಬೆನ್

This word is broken in coretext. Correct in harfbuzz

**Comment by brawer** [comment]
Thanks for the report! Added a test case that expects this rendering:

![image](https://cloud.githubusercontent.com/assets/1527880/23660130/b2ac06de-0348-11e7-98f6-c09e33724689.png)

**Comment by MayuraVerma** [comment]
Apple bugreport: 27837509
