### ISSUE TITLE
Test Case for Kannada 9

### ISSUE THREAD

**Issue by MayuraVerma** [unicode-org/text-rendering-tests#23]
"ಆ್ಯಕ್ಷಿಸ್‌"

Failed in Apple Core Text
Passed in Windows IE, EDGE
Passed in Chrome

Eg: "ಆ್ಯಕ್ಷಿಸ್‌" in this popular Kannada newspaper
http://www.prajavani.net/news/article/2017/03/09/476699.html
This website uses "Google Noto Sans Kannada" webfont.

Chrome
![chrome](https://cloud.githubusercontent.com/assets/14062593/23760180/925a757e-04b4-11e7-98f5-e93a9cb84c37.png)

Edge
![edge](https://cloud.githubusercontent.com/assets/14062593/23760179/925a8668-04b4-11e7-883f-01b9dd1c8600.png)

Safari
![safari](https://cloud.githubusercontent.com/assets/14062593/23760181/925c3468-04b4-11e7-9b4e-e2a08416d15b.png)

Apple bugtracker: 30948070

**Comment by brawer** [comment]
Thank you, much appreciated! If you know of similar problems for other scripts than Kannada, please don’t hesitate to report those too!

![image](https://cloud.githubusercontent.com/assets/1527880/24830129/1e4fda8c-1c80-11e7-88f0-40063e72f8ee.png)

**Comment by MayuraVerma** [comment]
Thank you.
