### ISSUE TITLE
Syntax error when testing fontkit on Travis

### ISSUE THREAD

**Issue by brawer** [unicode-org/text-rendering-tests#36]
When testing fontkit on the Travis continuous integration system, the wrapper script gives a Syntax error. Perhaps @devongovett knows how to fix this? Do we need to use a specific version of Node.js? See [here](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions) for how to specify a Node.js version in `.travis.yml` files.

https://travis-ci.org/unicode-org/text-rendering-tests/jobs/227862426#L566

```
/home/travis/build/unicode-org/text-rendering-tests/src/third_party/fontkit/render:3
let fontkit = require('fontkit');
    ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by devongovett** [comment]
Yeah v6 should work. I can also update the syntax of the render script to support older versions if needed.

**Comment by brawer** [comment]
> I can also update the syntax of the render script to support older versions if needed.

If it’s not too much work, that might be easiest. Thanks in advance. And congrats on the nice implementation, your test results are quite impressive!
