### ISSUE TITLE
SFNTQA proposal from Dec 2015

### ISSUE THREAD

**Issue by twardoch** [unicode-org/text-rendering-tests#40]
Just for reference, in 2014, I originally formulated a proposal for an "SFNTQA" test suite for OpenType fonts, and I’ve posted that proposal in December 2015 on the fontTools repo: 
https://github.com/fonttools/fonttools/issues/416

This repo has a slightly different, but related goal, so I’m just cross-linking that issue here.

**Comment by brawer** [comment]
Isn't SFNTQA (if it existed...) about testing font files? The goal of this project here is to

**Comment by twardoch** [comment]
I agree that these are mostly separate things, except for what I’d call “quirks” (in the meaning popularized by CSS implementations, notably old IE): there is the OpenType font format spec, and there are widely popularized rendering engines. But more often than not, in order to make an OpenType font work well in different rendering environments, the font developer has to implement “quirks”. 

A simple example would be mapping of various OpenType Layout behaviors (e.g. small caps or kerning for Cyrillic glyphs) into the `latn` languagesystem because older Adobe implementations did not perform any script itemization and only processed the `latn` languagesystem. There is even a flipside to this — there are fonts on the market which have Cyrillic small caps or kerning **only** in the `latn` languagesystem because they were then tested in an app such as InDesign, where this worked OK. There are tons of such things. 

Today, there is no easy way to identify and catalog these quirks. Some font writing tools silently infuse such quirks into fonts, other tools don’t unless the developer asks for them. Then, depending on which rendering engine you employ, problems may manifest because the font did or did not implement a given quirk. 

Operating system vendors (Microsoft, Apple, Google) may have a tendency (to a varying degree) to only implement the quirks that are required by their own rendering environments, but forego the quirks needed by other engines. 

This leads to confusion and a dillema: 

You may find yourself in a situation where you test the behavior of a given font and find that the results are different because the font implements a quirk which then some of the engines take advantage of while others don’t. Where would you then fix? Do you cross-pollute all engines with those quirks? This has mostly been the practice so far. 

For complex script processing, the default way of dealing with those things was to take Microsoft Uniscribe and then reimplement its quirks into other engines like HarfBuzz. Uniscribe ignores the order of lookups defined in the font and applies them in a hardcoded order? We'll do the same. Uniscribe resets the advance widths of some glyphs to 0? We'll do the same. And so on. 

So the question is: if both a font and a layout engine employs a quirk which is not really documented anywhere, and it yields "expected" behavior but through "unexpected" means — is it "good"? It may be "good" from one point of view (the users don't see a problem), but it isn't "good" from another point of view (the fonts don't actually conform to the public specs). 

Just like the CSS processors in browsers did, at some point they made an effort to catalog the quirks and then to eliminate them in next-generation implementations. With fonts, we're facing the situation where some quirks that used to be necessary 15 years ago no longer are — but the majority of font developers may not know this. So they keep putting these quirks in. 

Because of the quirks, it's currently hard to tell which side is at fault. If we see a discrepancy between how different rendering engines interpret a given font, it would be very useful to be able to classify these discrepancies into two categories: 

1. The font is faulty: the font doesn't follow the spec but uses some odd quirks that makes some engines forego the problem and render functionally "good" results — but it doesn’t necessary mean that all engines should do the same thing. 
2. The engine is faulty: the font is actually faithful to the spec and the engine seriously misinterprets some font data, so it should be fixed. 

So — I’m not sure how, but I think we should have a way to test font files and engines side-by-side, and in particular, have a way to mark-up/categorize the kinds of problems, i.e. say "why" there is some fail. 

This again is similar to the question of programming languages and interpreters. If you write Python code, there may be situations when your Python code is actually "wrong", but there may be situations where it's right but for some reason it will cause problems with either CPython 2.7 or CPython 3.6 or PyPy or some other engine. In theory, the code is right and the engines are wrong. In practice, it'll take years for the engine to be fixed so you may change your code, i.e. employ a quirk. 

It’s still useful to **know** which fix to your font was "genuine" and which was a "quirk" because, maybe, in 10 years, you’d remake the font differently (you'd keep the genuine fix but you'd skip the quirk). 

So — I’m thinking aloud how this could be solved. SFNTQA hasn't yet happened, "text-rendering-tests" does work to some extent, but isn't hugely extensive. So we might try to come up with a way to define the tests/checks in a way that benefit both sides (a font checker and an engine checker).
