### ISSUE TITLE
Add test case for cvar with shared points

### ISSUE THREAD

**Issue by brawer** [unicode-org/text-rendering-tests#43]
@jenskutilek, would you be OK contributing your `cvar` test font from https://github.com/fonttools/fonttools/pull/1113#issuecomment-347219995 to [Unicode’s test suite for text rendering](https://github.com/unicode-org/text-rendering-tests)? Ideally you could send a pull request for adding a font `TestCVAROne.ttf` to the [test fonts directory](https://github.com/unicode-org/text-rendering-tests/tree/master/fonts). The font can be a small subset (just the `o` and `n` glyphs would be enough). I’d then add a test case around your font. By contributing your test font, you’d help to make sure that all implementations correctly handle `cvar` tables.

**Comment by jenskutilek** [comment]
Of course. I've added the fonts in #44. They can also be used to trigger the Illustrator bug (#42) as they use the same gvar table.

**Comment by brawer** [comment]
Thanks again. Added test cases [CVAR-1](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#CVAR-1) and [CVAR-2](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#CVAR-1) a while ago, so I’m closing this issue.
