### ISSUE TITLE
A test case for `trak`?

### ISSUE THREAD

**Issue by ebraminio** [unicode-org/text-rendering-tests#46]
As your great work on providing `morx` test cases, I wonder if it is possible to have some tests for `trak` also? The list of fonts providing it are listed [here](https://gist.github.com/ebraminio/12e7a7dac0bf3404b1a74be45f4b0dc0). Some `kerx` ones also would be nice.

**Comment by brawer** [comment]
👍 Can you build test fonts?

**Comment by ebraminio** [comment]
To be honest I wanted your help on this. The way it works is with a simple table like this (ttx format), and [here](https://gist.github.com/ebraminio/12e7a7dac0bf3404b1a74be45f4b0dc0) is Apple fonts with `trak` but I couldn't get a tangible result when playing with the values when converting ttx to ttf back and forth.

Btw which font of this repository is considered as a template for the creating a new one and what is the common process of creating a test?

```xml
  <trak>
    <version value="1.0"/>
    <format value="0"/>
    <horizData>
      <trackEntry value="0.0" nameIndex="0">
        <track size="1.0" value="150"/>
        <track size="100.0" value="200"/>
      </trackEntry>
    </horizData>
    <vertData>
    </vertData>
  </trak>
```

**Comment by ebraminio** [comment]
Interesting that Mozilla's `trak` implementation is hide behind a `((hasMort || has MORX) && !(hasGSUB || hasKERX)) || hasAppleKerning` https://dxr.mozilla.org/mozilla-beta/source/gfx/thebes/gfxMacPlatformFontList.mm#185-196

[TestTRAK.ttf.zip](https://github.com/unicode-org/text-rendering-tests/files/1780537/TestTRAK.ttf.zip)

![screen shot 2018-03-05 at 2 25 44 pm](https://user-images.githubusercontent.com/833473/36971528-5738c380-2081-11e8-80f1-8bfd0364fdbd.png)

(current HarfBuzz implementation, Firefox, Chrome, Safari)

I wonder why `trak` of this font had not effect on Safari [and other OS apps] rendering, `TestTRAK` was based on `TestMORXOne` and apparently Font Book doesn't like its `name` table,

![screen shot 2018-03-05 at 2 31 11 pm](https://user-images.githubusercontent.com/833473/36971723-f76f86b8-2081-11e8-880a-b61272732cdd.png)

I think either that is related or there are some condition on CoreText whether to apply `trak` (like the one on Firefox) or Firefox and HarfBuzz (hb implementation was based on Gecko) are wrong about how to it apply `trak` altogether.

(cc: @behdad, @jfkthame)

**Comment by behdad** [comment]
CoreText only applies trak to San Francisco and Apple Color Emoji fonts, as created internally only. Read comments in hb-coretext.cc.

**Comment by ebraminio** [comment]
The one linked above is used on harfbuzz and you apparently created one also https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/TestTRAKOne.ttf so lets close this :)

**Comment by brawer** [comment]
Btw, I haven’t yet figured out how to run the test case for `trak` within this test suite. The test runner creates a FreeType font and calls [FT_Set_Char_Size()](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Set_Char_Size) passing the nominal point size. Then, it gives that font to libraqm, which in turn calls HarfBuzz. For tracking to work, some component along that stack — either libraqm or the FreeType functions within HarfBuzz — would have to call `hb_font_set_ptem()`. See https://github.com/harfbuzz/harfbuzz/issues/1269.
