### ISSUE TITLE
test adobe world-ready composer

### ISSUE THREAD

**Issue by MayuraVerma** [unicode-org/text-rendering-tests#49]
Can we include adobe world-ready composer for testing?

**Comment by brawer** [comment]
Sure, anything. Just send a pull request :-)

**Comment by MayuraVerma** [comment]
Does your program test against adobe world-ready composer?

I don’t see flags for it?

I have found a lot of issues for Kannada language with AWRC.

Can we test those cases with your script against AWRC?

**Comment by MayuraVerma** [comment]
Sorry I don’t understand how this code works.

**Comment by brawer** [comment]
Oh, you’re talking about Adobe InDesign? To test an implementation like this, one would need to write a new test runner which returns SVG given the test string and font. (Just read the code, and see for exmaple how OpenType.js or FontKit are getting tested). But for testing a proprietary system, the owner (in this case, Adobe) would have to set this up and run it internally as part of their development process.

The good news is that Adobe already knows about the existence of this test suite (it’s a Unicode project, after all). If and when Adobe feels like they want to improve their current shaping implementation, they’ll have Kannada tests readily available.
