### ISSUE TITLE
Test Kannada ZWJ

### ISSUE THREAD

**Issue by brawer** [unicode-org/text-rendering-tests#5]
Make a test case for Kannada shaping with ZWJ. https://github.com/behdad/harfbuzz/issues/341 has sample strings.

**Comment by brawer** [comment]
@lianghai, since you [know a lot](https://github.com/behdad/harfbuzz/issues/347#issuecomment-267300564) about Kannada shaping, would you mind having a look at Unicode’s current tests? See test reports for [CoreText](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/CoreText.html#SHKNDA-1) and [HarfBuzz](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/FreeStack.html#SHKNDA-1). You’d be very welcome to [contribute](https://github.com/unicode-org/text-rendering-tests#contributing) to this test suite, also for other scripts than Kannada.

**Comment by lianghai** [comment]
Sure. Thank you for inviting me. I've added this project to my to-do list and will take some time to understand it then contribute.

**Comment by brawer** [comment]
Closing this bug since we now have many test cases for Kannada shaping.
