### ISSUE TITLE
Change vendor ID of test fonts

### ISSUE THREAD

**Issue by brawer** [unicode-org/text-rendering-tests#53]
There’s now a freshly registered [Vendor ID](https://docs.microsoft.com/en-us/typography/vendors/#u) `UNIC` for the Unicode Consortium. For test fonts that were specially built for this test suite, change the font vendor ID to `UNIC`.

**Comment by moyogo** [comment]
What’ the rationale?

**Comment by brawer** [comment]
I’ve hacked up a bunch of test fonts from scratch, and added them to the test suite with `name` table entries to indicate copyright by Unicode and OFL-1.1 license. Currently, I believe some of those fonts carry vendor IDs of other foundries in the `OS/2` table, although those foundries didn’t produce them. Most are probably marked with an unknown vendor tag, which is less an issue; need to check. Maybe it’s also all fine.

**Comment by brawer** [comment]
Here’s what’s currently in the test fonts.

`ADBO` fonts/AdobeVFPrototype-Subset.otf
`ADBO` fonts/FDArrayTest257.otf
`ADBO` fonts/FDArrayTest65535.otf
`ADBO` fonts/TestGVARFour.ttf
`ADBO` fonts/TestHVAROne.otf
`ADBO` fonts/TestHVARTwo.ttf
`Alts` fonts/TestGVAREight.ttf
`Alts` fonts/Zycon.ttf
`DAMA` fonts/TestGLYFOne.ttf
`DAMA` fonts/TestGPOSOne.ttf
`GOOG` fonts/NotoSansBalinese-Regular.ttf
`GOOG` fonts/NotoSansKannada-Regular.ttf
`GOOG` fonts/NotoSerifKannada-Regular.ttf
`GOOG` fonts/TestCMAPMacTurkish.ttf
`GOOG` fonts/TestCVARGVAROne.ttf
`GOOG` fonts/TestCVARGVARTwo.ttf
`GOOG` fonts/TestGPOSFour.ttf
`GOOG` fonts/TestShapeAran.ttf
`GOOG` fonts/TestShapeEthi.ttf
`GOOG` fonts/TestShapeKndaV3.ttf
`MONO` fonts/TestGVAROne.ttf
`MONO` fonts/TestGVARThree.ttf
`MONO` fonts/TestGVARTwo.ttf
`MS ` fonts/Selawik-variable.ttf
`NONE` fonts/TestGSUBOne.otf
`UKWN` fonts/TestAVAR.ttf
`UKWN` fonts/TestCMAP14.otf
`UKWN` fonts/TestGPOSThree.ttf
`UKWN` fonts/TestGPOSTwo.otf
`UKWN` fonts/TestGSUBThree.ttf
`UKWN` fonts/TestGVARNine.ttf
`UKWN` fonts/TestKERNOne.otf
`UKWN` fonts/TestMORXEight.ttf
`UKWN` fonts/TestMORXEighteen.ttf
`UKWN` fonts/TestMORXEleven.ttf
`UKWN` fonts/TestMORXForty.ttf
`UKWN` fonts/TestMORXFour.ttf
`UKWN` fonts/TestMORXFourteen.ttf
`UKWN` fonts/TestMORXFourtyone.ttf
`UKWN` fonts/TestMORXNine.ttf
`UKWN` fonts/TestMORXOne.ttf
`UKWN` fonts/TestMORXSeventeen.ttf
`UKWN` fonts/TestMORXSixteen.ttf
`UKWN` fonts/TestMORXTen.ttf
`UKWN` fonts/TestMORXThirteen.ttf
`UKWN` fonts/TestMORXThirtyeight.ttf
`UKWN` fonts/TestMORXThirtyfive.ttf
`UKWN` fonts/TestMORXThirtyfour.ttf
`UKWN` fonts/TestMORXThirtynine.ttf
`UKWN` fonts/TestMORXThirtyone.ttf
`UKWN` fonts/TestMORXThirtyseven.ttf
`UKWN` fonts/TestMORXThirtysix.ttf
`UKWN` fonts/TestMORXThirtythree.ttf
`UKWN` fonts/TestMORXThirtytwo.ttf
`UKWN` fonts/TestMORXThree.ttf
`UKWN` fonts/TestMORXTwelve.ttf
`UKWN` fonts/TestMORXTwenty.ttf
`UKWN` fonts/TestMORXTwentyeight.ttf
`UKWN` fonts/TestMORXTwentyfive.ttf
`UKWN` fonts/TestMORXTwentyfour.ttf
`UKWN` fonts/TestMORXTwentynine.ttf
`UKWN` fonts/TestMORXTwentyone.ttf
`UKWN` fonts/TestMORXTwentyseven.ttf
`UKWN` fonts/TestMORXTwentysix.ttf
`UKWN` fonts/TestMORXTwentythree.ttf
`UKWN` fonts/TestMORXTwentytwo.ttf
`UKWN` fonts/TestMORXTwo.ttf
`UKWN` fonts/TestTRAKOne.ttf
`UNIC` fonts/TestShapeLana.ttf
`jens` fonts/TestGVAR-Composite-0.ttf
`jens` fonts/TestGVAR-Composite-Missing.ttf

**Comment by brawer** [comment]
Those with `UKWN` (which is not a registered tag) can be changed to `UNIC`.
