### ISSUE TITLE
TestHVAROne.otf has malformed GDEF

### ISSUE THREAD

**Issue by be5invis** [unicode-org/text-rendering-tests#58]
The data of this table is:

```
+0000 │ 00 01 00 03 00 0E 00 00 00 00 00 00 00 00 00 02 00 01 00 01 00 03 00 01
```

It looks like pointers for `markGlyphSetsDefOffset` and `itemVarStoreOffset` are missing.

**Comment by brawer** [comment]
Yes, this test case is about the zeroed-out pointers. See [description of test case HVAR-1](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#HVAR-1) and [FreeType bug 50170](https://savannah.nongnu.org/bugs/?50170).

**Comment by brawer** [comment]
Oh, now I see... the bug report is about GDEF, not HVAR!

**Comment by brawer** [comment]
Thanks for the bug report! Fixed.
