### ISSUE TITLE
Test font for CMAP-3 uses Croation language id instead of Turkish

### ISSUE THREAD

**Issue by wezm** [unicode-org/text-rendering-tests#64]
CMAP-3 says:

> The font for this test case contains a ‘cmap’ table of format 0, platform 1, encoding 0, language 18. Platform 1 means the classic Macintosh up to MacOS 9; the combination of encoding 0 and language 18 indicates the MacOS Turkish character encoding.

[According to the docs](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html) language id 18 is Croation, not Turkish as indicated:

<img src="https://user-images.githubusercontent.com/21787/104671128-49e9b880-5731-11eb-813f-db7b3677193e.png" alt="language ids" width="516">

Inspecting the font with ttx confirms that it is using language id 18 as well:

```xml
<cmap_format_0 platformID="1" platEncID="0" language="18">
```

**Comment by nedley** [comment]
18 is Turkish when used in a 'cmap' table, see [this comment](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html) in the spec:

> For such subtables, it is interpreted as one more than a QuickDraw language code, or zero if the subtable is language independent.

**Comment by wezm** [comment]
Oh wow, thanks for pointing that out. I had not noticed that sentence.
