### ISSUE TITLE
Addition of the Allsorts shaping engine

### ISSUE THREAD

**Issue by wezm** [unicode-org/text-rendering-tests#66]
Hello, I work on [Allsorts](https://github.com/yeslogic/allsorts), which is a font parsing and shaping engine implemented in [Rust](https://www.rust-lang.org/). Earlier this year I undertook the work to make is possible for execute this test suite against Allsorts via our [allsorts-tools binary](https://github.com/yeslogic/allsorts-tools). The test suite helped guide my implementation of glyph positioning and contour extraction, which were included in [the recent  0.6 release](https://yeslogic.com/blog/allsorts-rust-font-shaping-engine-0-6/). We don't yet support `morx` or variable fonts so a lot of the tests still fail but for the things we do support, they generally pass.

I'm opening this issue to discuss the possibility of incorporating Allsorts into the test suite. I have a commit [that adds Allsorts as an engine](https://github.com/yeslogic/text-rendering-tests/tree/allsorts) but I'm not sure how to go about integrating it like the other supported engines—suggestions welcome.

**Comment by brawer** [comment]
Very cool! Have a look at the test harness in [check.py](https://github.com/unicode-org/text-rendering-tests/blob/master/check.py). For fontkit and OpenType.js, it invokes an external binary, passing the path to the test font, the text to render, and some other parameters. The external binary then produces an SVG with the shaped text, and the test harness compares that to the expected outcome.

**Comment by wezm** [comment]
> For fontkit and OpenType.js, it invokes an external binary, passing the path to the test font, the text to render, and some other parameters. The external binary then produces an SVG with the shaped text, and the test harness compares that to the expected outcome.

Yep the external binary for Allsorts is https://github.com/yeslogic/allsorts-tools I already have it producing SVGs compatible with this repo. My main question was around how to integrate it into this project. Does this sound reasonable?

1. Add `allsorts-tools` as a submodule in `src/third_party`
1. Update the README to mention that Rust should be installed an link to <https://www.rust-lang.org/tools/install>
1. Update the `build` function in `check.py` to invoke `cargo` when building for the `Allsorts` engine
1. Pull in my other changes to support Allsorts as an engine from https://github.com/yeslogic/text-rendering-tests/commit/bd2fbdb8cdb7d69718df1a7f9ff2295259b8da03

**Comment by brawer** [comment]
Sounds good!
