### ISSUE TITLE
test for seac-like endchar command

### ISSUE THREAD

**Issue by Connum** [unicode-org/text-rendering-tests#77]
I just fixed a bug in opentype.js that could make for a new test case, see https://github.com/opentypejs/opentype.js/pull/633
The CFF `endchar` command supports a compatibility to the Type 1 `seac` command in order to implement standard encoding accented characters. This seems to also affect fontkit and it would help to be caught for other parsers/renderers as well.

**Comment by brawer** [comment]
Can you prepare a test font with just one or two glyphs? I'll then add a test case to the test suite.

**Comment by behdad** [comment]
> Can you prepare a test font with just one or two glyphs? I'll then add a test case to the test suite.

https://github.com/harfbuzz/harfbuzz/blob/main/test/api/fonts/cff1_seac.otf

**Comment by Connum** [comment]
Nice, that was fast! The harfbuzz test fonts are licensed under SIL Open Font License V1.1, so you can use them for the test suite.
